Ruby installer updates
StemboltHQ/docker-ci-images pull request #17
Opened 2017-06-13 22:15 UTC by andrewhood125

This adds ruby-2.3.4 and a few clean up items too. @jhawthorn @alexblackie @forkata

2017-06-14 23:16 UTC, Senjai requested changes

2017-06-14 23:16 UTC, Senjai commented on install_rubies.sh
> +RUBY_VERSIONS="2.3.0 2.3.1 2.3.4 2.2.2 2.2.3 2.2.5 2.1.6 2.1.7 2.1.10"
Nitpick here, for sanity sake, can we have this list be incremental?

2017-06-14 23:26 UTC, andrewhood125 commented on install_rubies.sh
> +RUBY_VERSIONS="2.3.0 2.3.1 2.3.4 2.2.2 2.2.3 2.2.5 2.1.6 2.1.7 2.1.10"
Happy to sort any which way. 👍

2017-06-15 00:08 UTC, Senjai commented on install_rubies.sh
> +RUBY_VERSIONS="2.3.0 2.3.1 2.3.4 2.2.2 2.2.3 2.2.5 2.1.6 2.1.7 2.1.10"
Either decremental or incremental just not both haha

2017-06-15 20:39 UTC, Senjai approved these changes

2017-06-15 20:40 UTC, merged